line/line-sdk-ios-swift

- LineSDK/LineSDK/Login/LoginManager.swift
- LineSDKSample/LineSDKSample/API/APIStore.swift
> private flag

- LineSDK/LineSDK.xcodeproj/project.pbxproj
- LineSDK/LineSDK/Crypto/Algorithms/ECDSA.swift
- LineSDK/LineSDK/Crypto/CryptoAlgorithm.swift
- LineSDK/LineSDK/Crypto/CryptoData.swift
- LineSDK/LineSDK/Crypto/CryptoHelpers.swift
- LineSDK/LineSDK/Crypto/JWK/JWA.swift
- LineSDK/LineSDK/Crypto/JWK/JWK.swift
- LineSDK/LineSDK/General/LineSDKError.swift
- LineSDK/LineSDK/Graph/Request/GetFriendsRequest.swift
- LineSDK/LineSDK/Login/LoginProcess.swift
- LineSDK/LineSDK/Messaging/Model/Flex/Component/FlexMessageProperties.swift
- LineSDK/LineSDK/Messaging/Model/Flex/Container/FlexBubbleContainer.swift
- LineSDK/LineSDK/Messaging/Model/Flex/Style/FlexBlockStyle.swift
- LineSDK/LineSDK/Messaging/Model/Message.swift
- LineSDK/LineSDK/Utils/Result.swift
- LineSDK/LineSDKTests/Message/FlexComponentMessageTests.swift
- LineSDK/LineSDKTests/Message/FlexIconComponentTests.swift
- LineSDK/LineSDKTests/Message/FlexSeparatorComponentTests.swift
- LineSDK/LineSDKTests/Message/TemplateButtonsPayloadTests.swift
- LineSDK/LineSDKTests/Message/TemplateCarouselPayloadTests.swift
- LineSDK/LineSDKTests/Message/TemplateImageCarouselPayloadTests.swift
- LineSDK/LineSDKTests/Networking/AdapterTests.swift
They should be all internal changes so I guess it would be fine to merge.
@mrmaakun Some typos are related to public documentation, so please regenerate it after being merged.
> Fix a few typos in project

- LineSDK/LineSDK.xcodeproj/project.pbxproj
> Remove unnecessary deploy target setting

- LineSDK/LineSDK.xcodeproj/project.pbxproj
- LineSDK/LineSDK/Friendship/Request/GetBotFriendshipStatus.swift
- LineSDK/LineSDK/Login/LoginResult.swift
- LineSDK/LineSDK/Login/Model/AccessTokenVerifyResult.swift
- LineSDK/LineSDK/Login/Model/UserProfile.swift
- LineSDK/LineSDKObjC/Friendship/LineSDKGetBotFriendshipStatusResponse.swift
- LineSDK/LineSDKObjC/Login/LineSDKLoginPermission.swift
- LineSDK/LineSDKObjC/Login/LineSDKLoginResult.swift
- LineSDK/LineSDKObjC/Login/Model/LineSDKAccessTokenVerifyResult.swift
- LineSDK/LineSDKObjC/Login/Model/LineSDKUserProfile.swift
- LineSDK/LineSDKObjC/Utils/JSONConverter.swift
- LineSDK/LineSDKObjCInterfaceTests/LineSDKModelInterfaceTests.m
Make it easier to generate JSON representation for existing API models.
> Feature convenience methods

- LineSDK/LineSDK.xcodeproj/project.pbxproj
- LineSDK/LineSDK/General/LineSDKError.swift
- LineSDK/LineSDK/Networking/Images/ImageDownloader.swift
- LineSDK/LineSDK/Networking/Images/ImageManager.swift
- LineSDK/LineSDK/Networking/Images/ImageViewExtension.swift
This adds an image downloaders and an in-memory cache mechanism for holding some images.
> Add image downloader helpers and memory cache

- LineSDK/LineSDK/Login/Model/AccessToken.swift
- LineSDK/LineSDK/Utils/Result.swift
- LineSDK/LineSDK/Utils/ResultUtils.swift
- LineSDK/LineSDKObjC/Utils/ResultExtensions.swift
Review for correct, clear English in code comments, since they're included in our online reference docs.
> Review code comments

- LineSDK/LineSDK/SharingUI/PageTabView.swift
- LineSDK/LineSDK/SharingUI/PageViewController.swift
- Add PageTabView normal / selected color and font style
> Add PageTabView normal / selected style

- LineSDK/LineSDK/SharingUI/ShareTargetSearchResultViewController.swift
- LineSDK/LineSDK/SharingUI/ShareTargetSelectingViewController.swift
- Init ShareTargetSearchResultViewController with must-have property: store
> ShareTargetSearchResultViewController little refactor

- LineSDK/LineSDK/SharingUI/ColumnDataStore.swift
- LineSDK/LineSDK/SharingUI/ShareRootViewController.swift
- LineSDK/LineSDK/SharingUI/ShareTarget.swift
- LineSDK/LineSDK/SharingUI/ShareViewController.swift
- LineSDKSample/LineSDKSample/UI/SampleUIHomeViewController.swift
This PR adds actual action for sending messages to selected targets when pressing the send button. @eJamesLin Please check it when you have time.
> Add sending message action and related delegate methods

- LineSDK/LineSDK.xcodeproj/project.pbxproj
- LineSDK/LineSDK/SharingUI/MessageShareTargetType.swift
- LineSDK/LineSDK/SharingUI/ShareViewController.swift
- LineSDK/LineSDK/SharingUI/ShareViewControllerDelegate.swift
- LineSDK/LineSDKObjC/Messaging/LineSDKMessage.swift
- LineSDK/LineSDKObjC/SharingUI/LineSDKMessageShareAuthorizationStatus.swift
- LineSDK/LineSDKObjC/SharingUI/LineSDKMessageShareTargetType.swift
- LineSDK/LineSDKObjC/SharingUI/LineSDKShareTarget.swift
- LineSDK/LineSDKObjC/SharingUI/LineSDKShareViewController.swift
- LineSDK/LineSDKObjC/SharingUI/LineSDKShareViewControllerDelegate.swift
- LineSDK/LineSDKObjC/Social/LineSDKUser.swift
- LineSDK/LineSDKObjCInterfaceTests/LineSDKModelInterfaceTests.m
- LineSDK/LineSDKObjCInterfaceTests/LineSDKViewControllerInterfaceTests.m
This defined all necessary public types and symbols for Objective-C compatibility. So users can bring up the sharing UI through Objective-C.
> Feature sharing objc support

- LineSDK/LineSDK/SharingUI/ShareTargetSearchResultViewController.swift
- Handle UIModalPresentationStyle.formSheet 
- Handle toggle software keyboard in simulator
> Search target selected panel view keyboard handling

- LineSDK/LineSDK/SharingUI/SelectedTargetPanelCell.swift
- Implement SelectedTargetPanelCell using autoLayout 
- Fix name label sizing issue
> SelectedTargetPanelCell AutoLayout

- LineSDK/LineSDKTests/Login/LoginFlowTests.swift
- Little about on the syntax at unit test
- Maybe using the ignore white space compare will be easier to do code review
https://github.com/line/line-sdk-ios-swift/pull/62/files?w=1
> Web page lang unit test little update

- LineSDK/LineSDK/Login/LoginManager.swift
- LineSDK/LineSDK/Networking/API.swift
Only reviewed parts that seem to have changed between Dec 2018 and 12 June 2019. No major changes. Let me know if I missed something big/important.
> Minor language fixes for v5.2

- LineSDK/LineSDK/Login/LoginManager.swift
- LineSDK/LineSDK/Networking/API.swift
API ReferenceでNoteが正しくレイアウトされない箇所がありました。
> Improve note layout

- LineSDK/LineSDK/Graph/Model/Group.swift
- LineSDK/LineSDK/Graph/Model/User.swift
- LineSDK/LineSDK/Graph/Request/GetFriendsRequest.swift
- LineSDK/LineSDK/SharingUI/Model/ColumnDataStore.swift
- LineSDK/LineSDK/SharingUI/Public/ShareViewController.swift
- LineSDK/LineSDK/SharingUI/Public/ShareViewControllerDelegate.swift
- LineSDK/LineSDKObjC/SharingUI/LineSDKShareViewController.swift
Tech writer's review. I suppose more review may be needed later, as work in v5.3 branch is still going on.
> Review v5.3 code comments

- LineSDK/LineSDKObjC/Login/LineSDKLoginButton.swift
- Align swift version login behavior
- https://github.com/line/line-sdk-ios-swift/blob/master/LineSDK/LineSDK/Login/LoginButton.swift#L213
> Fix login button behavior at objc wrapper

- fastlane/Fastfile
> Remove build setting workaround for Xcode 11 beta 4

- fastlane/Fastfile
- jazzy-templates/linedevdocs/assets/js/jazzy.js
@onevcat In order to avoid seeing file changes from the `last updated` date, I've added code to only display the copyright information in the footer for all pages. I've also modified the `Fastfile` to add the last updated date only on the `index.html` page.
> modified footer

- LineSDK/LineSDK/General/LineSDKError.swift
- LineSDK/LineSDK/Graph/Request/GetShareFriendsRequest.swift
- LineSDK/LineSDK/Graph/Request/GetShareGroupsRequest.swift
- LineSDK/LineSDK/LineSDKUI/LoginButton.swift
- LineSDK/LineSDK/LineSDKUI/SharingUI/Public/ShareViewController.swift
- LineSDK/LineSDK/Login/LoginManagerParameters.swift
- LineSDK/LineSDK/Login/LoginPermission.swift
Reviewing/editing code comments for the sake of SDK reference docs.
> Tech writer's review

- .travis.yml
- LineSDK/LineSDK/Crypto/CryptoHelpers.swift
- LineSDK/LineSDK/General/LineSDKError.swift
- LineSDK/LineSDK/LineSDKUI/LoginButton.swift
- LineSDK/LineSDK/Login/LoginManager.swift
- LineSDK/LineSDK/Login/LoginManagerParameters.swift
- LineSDK/LineSDK/Login/LoginProcess.swift
- LineSDK/LineSDKObjC/LineSDKUI/LineSDKLoginButton.swift
- LineSDK/LineSDKObjC/Login/LineSDKLoginManager.swift
- LineSDK/LineSDKObjCInterfaceTests/LineSDKModelInterfaceTests.m
- LineSDKSample/LineSDKSample.xcodeproj/project.pbxproj
- LineSDKSample/LineSDKSample/Base.lproj/Main.storyboard
- LineSDKSample/LineSDKSample/LineSDKSample.entitlements
- LineSDKSample/LineSDKSample/Login/LoginViewController.swift
@eJamesLin I reworked the support for macCatalyst. Some related screenshot below:
Please review and try to see whether it works for you!
> Support macCatalyst

- LineSDK/LineSDK/Crypto/Algorithms/ECDSA.swift
- LineSDK/LineSDK/Crypto/Algorithms/RSA.swift
- LineSDK/LineSDK/Crypto/CryptoAlgorithm.swift
- Extract common digest algorithm logic
- Easier to calculate `sha256` for https://github.com/line/line-sdk-ios-swift/pull/133  by `data.digest(using: DigestAlgorithm.sha256)`
> Extract common digest algorithm logic

- LineSDK/LineSDK/LineSDKUI/SharingUI/Public/ShareViewController.swift
Improved some wordings and fixed some formatting.
> Fix code comments

- LineSDK/LineSDK.xcodeproj/project.pbxproj
- LineSDK/LineSDK.xcodeproj/xcshareddata/xcschemes/LineSDK.xcscheme
- LineSDK/LineSDK.xcodeproj/xcshareddata/xcschemes/LineSDKObjC.xcscheme
- LineSDK/LineSDK.xcodeproj/xcshareddata/xcschemes/LineSDKObjCBinary.xcscheme
- LineSDK/LineSDK/LineSDKUI/SharingUI/TargetSearch/ShareTargetSearchResultTableViewController.swift
- LineSDK/LineSDK/LineSDKUI/SharingUI/TargetSearch/ShareTargetSearchResultViewController.swift
- LineSDKSample/LineSDKSample.xcodeproj/project.pbxproj
- LineSDKSwift.podspec
- README.md
Upgrade deploy target to Xcode 14's minimal supported version. Remove unused header file.
> Xcode 14 support

- LineSDK/LineSDK.xcodeproj/project.pbxproj
- LineSDK/LineSDK/Resource.bundle/PrivacyInfo.xcprivacy
Added the privacy manifest that LINE SDK is using.
> Add privacy manifest

- LineSDK/LineSDK/Crypto/JWT/JWTCoder.swift
- LineSDK/LineSDK/LineSDKUI/SharingUI/PageViewController/PageTabView.swift
- LineSDK/LineSDK/LineSDKUI/SharingUI/TargetSearch/ShareTargetSearchResultViewController.swift
As Swift 6 compiler suggested.
> Fix Xcode 16 compiling warnings

- LineSDK/LineSDKTests/LineSDKErrorTests.swift
- Add comprehensive tests for error description coverage across all LineSDKError reason types
- Ensure all error reasons provide valid, non-empty descriptions
- Add tests for error userInfo validation where applicable
> Add comprehensive error description tests

- LineSDK/LineSDK/LineSDKUI/OpenChatUI/Public/OpenChatCreatingController.swift
- LineSDK/LineSDKTests/Login/LoginManagerTests.swift
- LineSDK/LineSDKTests/OpenChat/OpenChatControllerTests.swift
Improve test coverage for `OpenChatCreatingController`.
> Improve OpenChatCreatingController test coverage and simplify test structure
