line/line-sdk-ios-swift

LineSDK/LineSDK/Networking/Client/ChainedPaginatedRequest.swift
LineSDK/LineSDKTests/Networking/ChainedPaginatedRequestsTests.swift

We need a way to refresh a long list whenever a page arrives. `onPageLoaded` would notify the subscriber for that exact event.

Add onPageLoaded callback to paginated request

---

LineSDK/LineSDK.xcodeproj/project.pbxproj
LineSDK/LineSDK/SharingUI/PageTabView.swift
LineSDK/LineSDK/SharingUI/PageViewController.swift
LineSDK/LineSDK/SharingUI/ShareViewController.swift
LineSDK/LineSDKTests/UI/PageTabViewTests.swift

- Add underline indicator animation at the bottom of PageTabView to indicate the current selected tab
- The UIPageViewController `contentOffset` pattern will be reset, ex: `0->375->750->375->0`,
thus use a `currentProgress` and `currentDiff` to normalized it

Add PageTabView underline indicator

---

LineSDK/LineSDK.xcodeproj/project.pbxproj
LineSDK/LineSDK/SharingUI/SelectedTargetView.swift
LineSDK/LineSDK/SharingUI/ShareViewController.swift

- Add sharing selected target view
- Add slide in / out animation
- remove the mocked entry button later

Add sharing selected target view and slide in / out animation

---

LineSDK/LineSDK.xcodeproj/project.pbxproj
LineSDK/LineSDK/SharingUI/ShareTargetSearchResultTableViewController.swift
LineSDK/LineSDK/SharingUI/ShareTargetSearchResultViewController.swift
LineSDK/LineSDK/SharingUI/ShareTargetSelectingViewController.swift

- Rename `ShareTargetSearchResultTableViewController` to `ShareTargetSearchResultViewController`
- For easier add selected panel view to search result table viewController, add a viewController to hold the original `ShareTargetSearchResultTableViewController`
- the main change part could be view in the commit: https://github.com/line/line-sdk-ios-swift/commit/cd95abc6f4f33b2a1c3224713df288d6c285a0fb

Preparation for selected panel

---

LineSDK/LineSDK.xcodeproj/project.pbxproj
LineSDK/LineSDK/SharingUI/ShareRootViewController.swift
LineSDK/LineSDK/SharingUI/ShareViewController.swift

- Extract ShareRootViewController, for not doing view / life cycle stuff in UINavigationController
- Basically move logic into ShareRootViewController, leave only styling in ShareViewController(UINavigationController)

Extract ShareRootViewController

---

LineSDK/LineSDK/SharingUI/ShareTargetSearchResultTableViewController.swift
LineSDK/LineSDK/SharingUI/ShareTargetSearchResultViewController.swift
LineSDK/LineSDK/SharingUI/ShareTargetSelectingViewController.swift

Currently, the search result table orders the sections in `[.friends, .groups]`. This PR adds support for reordering the sections. If users enter the search screen from the Group tab, the search result will place `.groups` first, then `friends`. This improves UX a bit.

Order the search result section

---

LineSDKSwift.podspec

CocoaPods 1.7.0 adds `swift_versions` for libraries to support multiple Swift versions.
Since this library supports both Swift 4.2 and 5.0, I suggest adding this property in podspec.

Add swift_versions for CocoaPods 1.7.0 & Swift 5.0

---

LineSDK/LineSDK/Login/Model/AccessToken.swift
LineSDK/LineSDK/Networking/API.swift
LineSDK/LineSDKObjC/Login/Model/LineSDKAccessToken.swift
LineSDK/LineSDKObjC/Networking/LineSDKAPI.swift
LineSDK/LineSDKObjCInterfaceTests/LineSDKAPIInterfaceTests.m
LineSDK/LineSDKObjCInterfaceTests/LineSDKModelInterfaceTests.m
LineSDK/LineSDKTests/API/PostRefreshTokenRequestTests.swift
LineSDK/LineSDKTests/API/PostTokenExchangeRequestTests.swift
LineSDKSample/LineSDKSample/Login/UserDetailViewController.swift

The refresh token is not intended to be used outside of the SDK itself. So we made it unavailable. 
The `@available` mark is for upgrading migration for now. Later we should rename the `_refreshToken` to an internal `refreshToken`.

Make refresh token non-public

---

LineSDK/LineSDK/Login/LoginManager.swift
LineSDK/LineSDK/Login/LoginProcess.swift
LineSDK/LineSDKObjC/Login/LineSDKLoginManager.swift
LineSDK/LineSDKObjCInterfaceTests/LineSDKModelInterfaceTests.m
LineSDK/LineSDKTests/Login/LoginFlowTests.swift

@wangzun123 This PR adds support for setting language of the web page used for web login. Please check it when you have time.

Customizable web page login language

---

LineSDK/LineSDK/SharingUI/Public/ShareViewController.swift
LineSDK/LineSDK/SharingUI/Public/ShareViewControllerDelegate.swift

This PR adds the ability to call the `didCancel` delegate method when user dismiss the sharing UI by swipe down gesture in iOS 13.
In earlier iOS versions, users can only dismiss a model by tapping the "Cancel" button. In iOS 13, they can also dismiss it by gesture by default. This provides the correct delegate invoking for that case.

Cancel presenting by gesture also triggers delegate method

---

LineSDKSample/LineSDKSample/UI/SampleUIHomeViewController.swift

- Remove the extra dismiss in sample proj, since the dismiss action are covered inside SDK.
- This also let iOS 12 and below, could see the `User Cancelled` alert.
- The `presentedViewController` is `nil` in 
```swift
// SampleUIHomeViewController.swift
func shareViewControllerDidCancelSharing(_ controller: ShareViewController) {
}
```

Fix iOS 12 is not showing the `User Cancelled` message

---

LineSDK/LineSDK/Login/LoginButton.swift
LineSDK/LineSDK/Utils/Constant.swift
LineSDK/LineSDK/Utils/Helpers.swift
LineSDKSwift.podspec

- Based on the suggestion from https://github.com/line/line-sdk-ios-swift/issues/76
- `resource_bundles` is recommended by CocoaPods over `resources`
- Since LINE SDK is integrated using dynamic framework, resource will be under separated framework, thus we might not have the same duplicated resource in main bundle issues as describe. 
But still `resource_bundles` is a better way.

Support CocoaPods resource bundles

---

LineSDK/LineSDK/Crypto/GetDiscoveryDocumentRequest.swift
LineSDK/LineSDK/Login/LoginManager.swift

- When verifying token, get the issuer metadata from open ID discovery document, instead of a fixed value.
- https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderMetadata

Adopt provider metadata issuer from discovery document when doing token verification

---

LineSDK/LineSDK/Login/Model/AccessToken.swift
LineSDK/LineSDK/Networking/API.swift
LineSDK/LineSDKTests/Login/LoginManagerTests.swift

In the current version, when a token is refreshed, the stored ID token inside it will be discarded as well. This is due to the received token in refreshing does not contain the open ID field.
The ID token contains some useful information like user ID, display name and email, so we'd like to keep it as long as possible. It gives users a way to get this information in a sync way.

Keep ID Token while refreshing

---

LineSDK/LineSDK/General/LineSDKError.swift
LineSDK/LineSDK/Login/LoginConfiguration.swift
LineSDK/LineSDK/Login/LoginManager.swift
LineSDK/LineSDK/Login/LoginProcess.swift
LineSDK/LineSDKTests/Login/LoginConfigurationTests.swift
LineSDK/LineSDKTests/Login/LoginManagerTests.swift

`.sourceApplication` is not provided anymore on iOS 13 if the destination app and source app not in the same app group. I guess it is for privacy consideration, but it indeed breaks our implementation on source app verification now.
This PR removes the double-check on the source app.

Remove source application check due to not supported on iOS 13

---

LineSDK/LineSDK/Login/LoginManager.swift
LineSDK/LineSDK/Login/LoginProcess.swift
LineSDK/LineSDK/Login/LoginResult.swift
LineSDK/LineSDKTests/Login/LoginManagerTests.swift

This provides a way to access the ID Token nonce in the login result. By this, users can verify the ID token against our server with the nonce checking.

Add IDTokenNonce as public var in login result

---

LineSDK/LineSDK/LineSDKUI/SharingUI/PageViewController/PageTabView.swift
LineSDK/LineSDK/LineSDKUI/SharingUI/PageViewController/PageViewController.swift

`UIPageViewController.viewControllers` are not 100% correct when:
* Swipe over a page and bounce back, or
* Interrupt a swipe but swipe again before it is reset to origin.
Ref: http://www.openradar.me/22833651 and https://stackoverflow.com/questions/36853129/uipageviewcontroller-can-return-the-wrong-index
At the same time, `pageViewController(_:didFinishAnimating:previousViewControllers:transitionCompleted:)` is not always called, especially when in the case of "swiping over a page and letting it bounce back". 
In this PR, I tried to fix these two issues. 
1. Instead of using `UIPageViewController.viewControllers`, now we rely on the `currentProgress` to set the tab index.
2. Choose to use `scrollViewDidEndDecelerating` to trigger this tab update.

Use currentProgress to determine tab selection state when scroll view done

---

LineSDK/LineSDK/LineSDKUI/SharingUI/PageViewController/PageViewController.swift

When switching tab while tapping the page tab, if you do other UI action (such as bringing search view by tapping the search bar, or stoping the scrolling animation by hold the page view), we may fall to some strange UI states. It is basically a conflicting of the page view controller bugs and the poor UIKit state management.
This PR fixes the case by blocking user interaction when the scrolling animation happens.

Fix scrolling issue when tapping page tab

---

LineSDK/LineSDK/LineSDKUI/SharingUI/TargetSearch/ShareTargetSearchResultViewController.swift

On iOS 13, when layout the tableview while it is not yet in the view hierarchy, a runtime warning will be given. This PR delayed the view layout (for selection panel) to `viewDidLayoutSubviews`, to avoid the warning.
At the same time, it would be better to use system method instead of a hard coded duration to wait for system view layout done.

Fix panel layout warning on iOS 13

---

LineSDK/LineSDK/LineSDKUI/SharingUI/PageViewController/PageViewController.swift

Fix a rare case which may freeze the UI when `decelerate` is `false` when stopping dragging in the page view. This happens randomly when you scroll the page in a very small distance.

Enable user interface when no decelerate happens

---

LineSDK/LineSDK/General/LineSDKError.swift

I received a complaint about getting the error detail code. This fixes #114.

Mark `APIErrorDetail` properties as public

---

LineSDK/LineSDK/Crypto/CryptoAlgorithm.swift
LineSDK/LineSDK/Login/LoginProcess.swift

- Extract the `randomData(bytesCount:)` from PKCE PR https://github.com/line/line-sdk-ios-swift/pull/133
- Cherry-pick the `randomData(bytesCount:)` adoption to state and default nonce https://github.com/line/line-sdk-ios-swift/commit/29c240cf59939e51c2f21cd57da41f30e7908518
- In this way, the PR could focus on single change

Random data generator

---

Gemfile.lock
README.md
fastlane/Pluginfile

As #59 was merged a year ago, and there's [no more new coverage report](https://codecov.io/gh/line/line-sdk-ios-swift) sent to Codecov, this PR further cleans up Codecov leftovers.

Remove everything codecov

---

jazzy-templates/linedevdocs/templates/header.mustache

Updated the header navigation:
- Title link _LINE SDK Docs_ now points to [iOS Swift reference top](https://developers.line.biz/en/reference/ios-sdk-swift/) (and not [Developers Site references overview](https://developers.line.biz/en/reference/) anymore)
- Header links changed to _LINE Developers Site_ and _github releases page_

Update header navigation links

---

LineSDK/LineSDK.xcodeproj/project.pbxproj
LineSDK/LineSDK/Utils/Colors.swift
LineSDK/LineSDKTests/Message/UIColorExtensionTests.swift

- `scanHexInt32` is deprecated at iOS 13, changed to `scanHexInt64`
- add UIColorExtensionTests
- remove internal UIColor extension hex3 and hex4, which are not used in SDK.
- [In iOS 11 and later, all apps use the 64-bit architecture.](https://developer.apple.com/documentation/uikit/app_and_environment/updating_your_app_from_32-bit_to_64-bit_architecture)

`scanHexInt32` API deprecated

---

LineSDK/LineSDKObjC/Login/Model/LineSDKAccessToken.swift
LineSDK/LineSDKObjCInterfaceTests/LineSDKModelInterfaceTests.m

This should solve #185 
The lack of raw string value of ID Token is unexpected. This PR adds the capability of getting the raw value, so the client can send it to the verify server easier to go through the verifying process.

Add a getter for raw IDToken in ObjC wrapper

---

LineSDK/LineSDK/Friendship/Request/GetBotFriendshipStatus.swift
LineSDK/LineSDK/Login/LoginManagerOptions.swift
LineSDK/LineSDK/Login/LoginManagerParameters.swift
LineSDK/LineSDK/Login/LoginResult.swift
LineSDK/LineSDK/Networking/API/API.swift
LineSDKSample/LineSDKSample/API/APIStore.swift
LineSDKSample/LineSDKSample/Login/LoginSettingsViewController.swift

We now call the bot as "LINE Official Account". This updates the API reference in doc comment to reflect the change.

Update the comment doc for official account terminology change

---

fastlane/Fastfile

As verified as below:
For now, we only support exporting the xcframework locally from the releasing machine. Maybe later we can find a CI node to run the release script and allow the cert be read from the host.
But as the first step, we now sign it when releasing and it follows [the session](https://developer.apple.com/videos/play/wwdc2023/10061/) and allows users to verify our product.

Sign the xcframework artifacts with distribution cert

---

fastlane/Fastfile

This fixes #209 
The script we are using to create the xcframework is using `true` as the default value for bit code. We need to pass in the `false` to disable this behavior.

Explicitly disable bitcode

---

LineSDK/LineSDK/Login/LoginManagerParameters.swift
LineSDK/LineSDK/Login/LoginProcess.swift
LineSDK/LineSDKObjC/Login/LineSDKLoginManagerParameters.swift
LineSDK/LineSDKObjCInterfaceTests/LineSDKModelInterfaceTests.m
LineSDK/LineSDKTests/Login/LoginFlowTests.swift
LineSDK/LineSDKTests/Login/LoginManagerTests.swift
LineSDKSample/LineSDKSample/Login/LoginSettingsViewController.swift

Use this setting, users can specify which auth method (email&password or QR code) should be preferred as the first screen when performing web login.
Sample usage:
```swift
var parameters = LoginManager.Parameters()
parameters.initialWebAuthenticationMethod = .qrCode
LoginManager.shared.login(parameters: parameters) { result in
// Handle result.
}
```
By default, `.email` is used to keep the current behavior unchanged.
Also some refactoring of internal affairs, to make the interface more stable in future when we need to add more login parameters.

Add a parameter for setting `initialWebAuthenticationMethod`

---

LineSDK/LineSDKTests/Login/LoginFlowTests.swift
LineSDK/LineSDKTests/Login/LoginManagerTests.swift

This PR improves the test coverage and simplified some test code.
- Add comprehensive test coverage for exchangeToken error handling and retry mechanism
- Add comprehensive window management tests
- Refactor LoginManagerTests to eliminate code duplication

Refactor and improve test coverage a bit

---

.github/workflows/coverage.yaml

This skip the coverage workflow when PR. It reduces some resource usage since we only want to update the coverage badge for master.

Do not trigger coverage CI when PR

---

LineSDK/LineSDK.xcodeproj/project.pbxproj
LineSDK/LineSDK/LineSDKUI/SharingUI/TargetSelecting/ShareRootViewController.swift
LineSDK/LineSDKTests/Sharing/ShareRootViewControllerTests.swift

This PR significantly improves the test coverage for the sharing functionality, ensuring better reliability and maintainability of the ShareRootViewController component.
- Add comprehensive unit tests for `ShareRootViewController` covering initialization, data loading, and user interactions
- Refactor ShareRootViewController to expose necessary properties for testing (store, allLoaded, sendMessage)
- Improve test coverage for sharing functionality with proper mocking and error handling

Add comprehensive unit tests for ShareRootViewController

---

LineSDK/LineSDK.xcodeproj/project.pbxproj
LineSDK/LineSDK/LineSDKUI/SharingUI/Model/ColumnDataStore.swift
LineSDK/LineSDK/LineSDKUI/SharingUI/TargetSearch/ShareTargetSearchResultTableViewController.swift
LineSDK/LineSDKTests/Sharing/ShareTargetSearchResultTableViewControllerTests.swift

Add comprehensive unit tests for `ShareTargetSearchResultTableViewController` to improve code coverage.
- Added 6 unit test cases covering core functionality
- Test search filtering, observer notifications, and table view methods
- Include mock objects and test data for reliable testing
- Fixed `handleSelectingChange` method coverage by properly setting up `filteredIndexes`
All 6 tests pass with 0 failures. Swift 6 compatible.

Add unit tests for ShareTargetSearchResultTableViewController

---

.github/workflows/ci.yaml
LineSDK/LineSDK/LineSDKUI/OpenChatUI/Public/OpenChatCreatingController.swift
LineSDK/LineSDKTests/OpenChat/OpenChatControllerTests.swift

- Add `presentingAnimation` parameter to `loadAndPresent` and `presentCreatingViewController` methods in `OpenChatCreatingController`
- Allow controlling animation for both view controller presentation and navigation controller push operations
- Update all unit tests to use `presentingAnimation: false` to improve test reliability and reduce timing issues
- Added optional `presentingAnimation: Bool = true` parameter to maintain backward compatibility
- Applied animation control to both `present(_:animated:completion:)` and `pushViewController(_:animated:)` calls
- Updated all test cases in `OpenChatControllerTests.swift` to explicitly disable animations during testing

Add presentingAnimation parameter to OpenChatCreatingController
